    
language: minimal


script:
  #- docker-compose -f docker-compose.yml build ofw
  - if [ $TRAVIS_BRANCH == "master" ]; then docker-compose -f docker-compose.yml build ofw; fi


before_deploy:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push garagon/optimization:amd
    on:
      branch: master
  - provider: script
    script: docker tag garagon/optimization garagon/optimization:amd_${TRAVIS_TAG} &&
      docker push garagon/optimization:amd_${TRAVIS_TAG}
    on:
      tags: true